INSERT INTO PF_FLUJOS (ID_FLUJO, FECHA_CREACION, ID_TIPO_FLUJO, ORDEN_ACTIVO, DESCRIPCION) VALUES (35, '01/06/16', 2, 1, 'Validación Director - Firma Presidente');
INSERT INTO PF_GRUPOS (ID_GRUPO, FIRMANTES_REQUERIDOS, ORDEN, ID_FLUJO, ID_TIPO_GRUPO, CERRADO) VALUES (68, 1, 1, 35, 1, 0);
INSERT INTO PF_GRUPOS (ID_GRUPO, FIRMANTES_REQUERIDOS, ORDEN, ID_FLUJO, ID_TIPO_GRUPO, CERRADO) VALUES (69, 1, 2, 35, 2, 0);
INSERT INTO PF_GRUPO_PERSONAS (ID_GRUPO_PERSONA, ID_GRUPO, ID_PERSONA, PERSONA_OBLIGATORIA, REALIZADO) VALUES (69, 68, 10, 0, 0); -- José Rafael Díaz
INSERT INTO PF_GRUPO_PERSONAS (ID_GRUPO_PERSONA, ID_GRUPO, ID_PERSONA, PERSONA_OBLIGATORIA, REALIZADO) VALUES (70, 69, 13, 0, 0); -- Ricardo Melchior
--
COMMIT;

-- Jacqueline
INSERT INTO PF_CIRCUITO_POR_PERSONA (ID_REGISTRO, ID_CIRCUITO, DNI_SOLICITANTE) VALUES (1011, 35, '43780595A');
-- Empleado Secretaría General
INSERT INTO PF_CIRCUITO_POR_PERSONA (ID_REGISTRO, ID_CIRCUITO, DNI_SOLICITANTE) VALUES (1012, 35, '11111111H');

COMMIT;