DROP TABLE PF_PERSONA_AUSENCIA;
DROP TABLE PF_PERSONA_REVISORES;
DROP TABLE PF_GRUPO_PERSONAS;
DROP TABLE PF_PROCESO_FIRMA;
DROP TABLE PF_PERSONAS ;
DROP TABLE PF_GRUPOS;
DROP TABLE PF_DOCUMENTOS;
DROP TABLE PF_FLUJOS ;
DROP TABLE PF_TM_ESTADO_DOCUMENTO;
DROP TABLE PF_TM_TIPO_FLUJO;
DROP TABLE PF_TM_TIPO_GRUPO;

CREATE TABLE PF_TM_ESTADO_DOCUMENTO(
	ID number(16,0) primary key,
	CODIGO varchar2(4),
	DESCRIPCION varchar2(25)
);
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (0,'PEND','Pendiente de circuito');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (1,'TRAM','En tramite');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (2,'FIRM','Firmado');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (3,'RECH','Rechazado');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (4,'ENVD','Enviado');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (5,'RECP','Recuperado');

CREATE TABLE PF_TM_TIPO_FLUJO(
	ID number(16,0) primary key,
	CODIGO varchar2(4),
	DESCRIPCION varchar2(25)
);
INSERT INTO PF_TM_TIPO_FLUJO (ID, CODIGO, DESCRIPCION) values (1,'GNRD','Generado');
INSERT INTO PF_TM_TIPO_FLUJO (ID, CODIGO, DESCRIPCION) values (2,'PRDF','Predefinido');

CREATE TABLE PF_TM_TIPO_GRUPO(
	ID number(16,0) primary key,
	CODIGO varchar2(4),
	DESCRIPCION varchar2(25)
);
INSERT INTO PF_TM_TIPO_GRUPO (ID, CODIGO, DESCRIPCION) values (1,'VALD','Validar');
INSERT INTO PF_TM_TIPO_GRUPO (ID, CODIGO, DESCRIPCION) values (2,'FIRM','Firmar');

CREATE TABLE PF_TM_ACCION(
	ID number(16,0) primary key,
	CODIGO varchar2(4),
	DESCRIPCION varchar2(25)
);
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (0,'ENVD','Enviar');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (1,'FIRM','Firmar');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (2,'VALD','Validar');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (3,'RECH','Rechazar');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (4,'BORR','Borrar');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (5,'RECP','Recuperar');


/*NUEVO*/
CREATE TABLE PF_CAT_BACKOFFICE(
	ID_BACKOFFICE number(16,0) primary KEY,
	CODIGO varchar2(10),
	DESCRIPCION varchar2(255),
	USERNAME varchar2(80)
);

CREATE TABLE PF_PERSONAS(
	ID_PERSONA number(16,0) primary key,
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDO1 VARCHAR2(50) NOT NULL,
	APELLIDO2 VARCHAR2(50),
	DNI_NIE VARCHAR2(10) NOT NULL,
	CARGO varchar2(50)
);

CREATE TABLE PF_FLUJOS (
	ID_FLUJO number(16,0) primary key,
	FECHA_CREACION date DEFAULT sysdate,
	ID_TIPO_FLUJO number(16,0) not null,
	ORDEN_ACTIVO number(2,0) DEFAULT 1,
	MAIL_CREADOR varchar2(255),
	DESCRIPCION varchar2(255),
	FOREIGN KEY (ID_TIPO_FLUJO) references PF_TM_TIPO_FLUJO(ID)
);

CREATE TABLE PF_DOCUMENTOS(
	ID_DOCUMENTO number(16,0) primary key,
	FECHA_SUBIDA_PORTAFIRMAS DATE DEFAULT sysdate,
	URI VARCHAR2(255) NOT NULL UNIQUE,
	DNI_SUBIDO_POR varchar2(9) NOT NULL,
	NOMBRE_SUBIDO_POR varchar2(50) NOT NULL,
	ID_FLUJO number(16,0),
	ID_ESTADO number(16,0) not null,
	COMUNICADO numeric(1),
	ASUNTO varchar2(4000),
	DOC_REL varchar2(255),
	ID_EXPEDIENTE varchar2(255),
	NOMBRE_DOCUMENTO varchar2(255),
	HASH varchar2(255),
	ID_BACKOFFICE_ORIGEN number(16,0),
	TIPO_FIRMA varchar2(5) DEFAULT 'XADES' not null,

	FOREIGN KEY (ID_BACKOFFICE_ORIGEN) REFERENCES PF_CAT_BACKOFFICE(ID_BACKOFFICE),
	FOREIGN KEY (ID_FLUJO) REFERENCES PF_FLUJOS(ID_FLUJO),
	FOREIGN KEY (ID_ESTADO) references PF_TM_ESTADO_DOCUMENTO(ID)
);

CREATE TABLE PF_DOCUMENTOS_WSDL(
	ID number(16,0) primary key,
	ID_DOCUMENTO number(16,0),
	URL varchar2(255),
	FOREIGN KEY (ID_DOCUMENTO) references PF_DOCUMENTOS(ID_DOCUMENTO)
);

CREATE TABLE PF_GRUPOS(
	ID_GRUPO number(16,0) primary key,
	FIRMANTES_REQUERIDOS number(2,0),
	ORDEN number(2,0),
	ID_FLUJO number(16,0),
	ID_TIPO_GRUPO number(16,0),
	CERRADO numeric(1) DEFAULT 0,
	FOREIGN KEY (ID_FLUJO) REFERENCES PF_FLUJOS(ID_FLUJO) ON DELETE CASCADE,
	FOREIGN KEY (ID_TIPO_GRUPO) REFERENCES PF_TM_TIPO_GRUPO(ID)
);

CREATE TABLE PF_GRUPO_PERSONAS(
	ID_GRUPO_PERSONA number(16,0) primary key,
	ID_GRUPO number(16,0),
	ID_PERSONA number(16,0),
	PERSONA_OBLIGATORIA numeric(1) DEFAULT 0,
	REALIZADO numeric(1) DEFAULT 0,
	FOREIGN KEY (ID_GRUPO) REFERENCES PF_GRUPOS(ID_GRUPO) ON DELETE CASCADE,
	FOREIGN KEY (ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA)
);

CREATE TABLE PF_AUSENCIA(
	ID_AUSENCIA number(16,0) primary key,
	ID_PERSONA number(16,0),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	FOREIGN KEY(ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA) 
);

CREATE TABLE PF_SUSTITUCION(
	ID_SUSTITUCION number(16,0) primary key,
	ID_PERSONA number(16,0),
	ID_AUSENCIA number(16,0),
	FOREIGN KEY(ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA),
	FOREIGN KEY(ID_AUSENCIA) REFERENCES PF_AUSENCIA(ID_AUSENCIA)  
);

CREATE TABLE PF_REVISION(
	ID_REVISION number(16,0) primary KEY,
	ID_PERSONA number(16,0),
	FOREIGN KEY (ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA) on DELETE CASCADE
);

CREATE TABLE PF_REVISOR(
	ID_REVISOR number(16,0) primary KEY,
	ID_PERSONA number(16,0),
	ID_REVISION number(16,0),
	FOREIGN KEY (ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA) on DELETE CASCADE,
	FOREIGN KEY (ID_REVISION) REFERENCES PF_REVISION(ID_REVISION) on DELETE CASCADE
);

CREATE TABLE PF_PROCESO_FIRMA(
	ID_PROCESO number(16,0) primary key,
	ID_DOCUMENTO number (16,0),
	ID_PERSONA number (16,0),
	ID_ACCION number(16,0),
	FECHA_ACCION date DEFAULT sysdate,
	OBSERVACIONES varchar2(255),
	FOREIGN KEY(ID_DOCUMENTO) REFERENCES PF_DOCUMENTOS(ID_DOCUMENTO),
	FOREIGN KEY(ID_PERSONA) REFERENCES PF_PERSONAS(ID_PERSONA),
	FOREIGN KEY(ID_ACCION) REFERENCES PF_TM_ACCION(ID)
);

CREATE TABLE PF_FIRMANTE_POR_PERSONA (
	ID_REGISTRO number(16,0) primary KEY,
	ID_PERSONA number(16,0),
	DNI_SOLICITANTE VARCHAR2(10) NOT NULL,
	FOREIGN KEY (ID_PERSONA) references PF_PERSONAS (ID_PERSONA)
);

/************* MODIFICACION PREVIA *************/
ALTER TABLE PF_GRUPO_PERSONAS MODIFY REALIZADO numeric(1) DEFAULT 0;
ALTER TABLE PF_FLUJOS MODIFY ORDEN_ACTIVO number(2,0) DEFAULT 1;
UPDATE PF_FLUJOS set ORDEN_ACTIVO = 1 WHERE ORDEN_ACTIVO = 0;
ALTER TABLE PF_PERSONAS ADD CARGO varchar2(80);


/************* MODIFICACION 08/07/2015 *************/
ALTER TABLE PF_PERSONAS ADD MAIL varchar2(255);
ALTER TABLE PF_PERSONAS ADD ES_FIRMANTE numeric (1) DEFAULT 0;
ALTER TABLE PF_PERSONAS ADD ES_VALIDADOR numeric (1) DEFAULT 0;
ALTER TABLE PF_FLUJOS ADD MAIL_CREADOR varchar2(255);
ALTER TABLE PF_FLUJOS ADD DESCRIPCION varchar2(255);

CREATE TABLE PF_CAT_BACKOFFICE(
	ID_BACKOFFICE number(16,0) primary KEY,
	CODIGO varchar2(10),
	DESCRIPCION varchar2(255),
	USERNAME varchar2(80)
);

ALTER TABLE PF_DOCUMENTOS ADD ID_BACKOFFICE_ORIGEN number(16,0);
ALTER TABLE PF_DOCUMENTOS ADD CONSTRAINT fk_CatBackOffice
FOREIGN KEY (ID_BACKOFFICE_ORIGEN) REFERENCES PF_CAT_BACKOFFICE(ID_BACKOFFICE);

CREATE TABLE PF_DOCUMENTOS_WSDL(
	ID number(16,0) primary key,
	ID_DOCUMENTO number(16,0),
	URL varchar2(255),
	FOREIGN KEY (ID_DOCUMENTO) references PF_DOCUMENTOS(ID_DOCUMENTO)
);


ALTER TABLE PF_DOCUMENTOS DROP COLUMN URL;

ALTER TABLE PF_DOCUMENTOS ADD
TIPO_FIRMA varchar2(5) DEFAULT 'XADES' not null;

/******** LIMPIAR BD ********/
DELETE FROM PF_DOCUMENTOS_WSDL;
DELETE FROM PF_PROCESO_FIRMA;
DELETE FROM PF_DOCUMENTOS;
DELETE FROM PF_FLUJOS WHERE ID_TIPO_FLUJO = 1;
/****************************/



/************* MODIFICACION 27/07/2015 *************/
ALTER TABLE PF_FLUJOS DROP COLUMN MAIL_CREADOR;
ALTER TABLE PF_DOCUMENTOS ADD MAIL_CREADOR varchar2(255);

ALTER TABLE PF_DOCUMENTOS MODIFY
ASUNTO varchar2(4000);

/************* MODIFICACION 05/08/2015 *************/

/************* MODIFICACION 08/09/2015 *************/
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (0,'ENVD','Enviar');
INSERT INTO PF_TM_ESTADO_DOCUMENTO (ID, CODIGO, DESCRIPCION) values (5,'RECP','Recuperado');
INSERT INTO PF_TM_ACCION (ID, CODIGO, DESCRIPCION) values (5,'RECP','Recuperar');

CREATE TABLE PF_FIRMANTE_POR_PERSONA (
	ID_REGISTRO number(16,0) primary KEY,
	ID_PERSONA number(16,0),
	DNI_SOLICITANTE VARCHAR2(10) NOT NULL,
	FOREIGN KEY (ID_PERSONA) references PF_PERSONAS (ID_PERSONA)
);

/************* MODIFICACION 14/09/2015 *************/

/************* MODIFICACION 26/10/2015 *************/
CREATE TABLE PF_CAT_DEPARTAMENTO (
	ID VARCHAR2(64) primary KEY,
	ACRONIMO VARCHAR2(10) NOT NULL,
	DESCRIPCION VARCHAR2(80) NOT NULL
);

ALTER TABLE PF_DOCUMENTOS ADD ID_DEPARTAMENTO VARCHAR2(64);
ALTER TABLE PF_DOCUMENTOS ADD CONSTRAINT fk_CatDepartamento
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES PF_CAT_DEPARTAMENTO(ID);

INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptExplotacion','EX','Explotación');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptInfraestructura','IN','Infraestructura');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptRecursosHumanos','RH','Recursos Humanos');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptGabinetePrensa','EX','Gabinete Prensa');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptEconomicoFinanciero','EF','Económico Financiero');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptAsistenciaJuridica','AJ','Asistencia Jurídica');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptDominioPublico','DP','Dominio Público');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptPresidencia','PR','Presidencia');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptDireccion','DI','Dirección');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptCalidad','MA','Calidad/Medioambiente');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptPlanificacionUrbanistica','PU','Planificación Urbanística');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptSecretariaGeneral','SG','Secretaría General');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptPlanificacionEstrategica','PE','Planificación Estratégica');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptComercial','CO','Comercial');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptFacturacion','FA','Facturación');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptDesarrolloSostenible','DS','Desarrollo Sostenible');
INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('dptPrevencionRiesgosLaborales','PRL','Prevención de Riesgos Laborales');
--INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('Director','DI','Gabinete Prensa');
--INSERT INTO PF_CAT_DEPARTAMENTO (ID, ACRONIMO, DESCRIPCION) values ('Presidente','PR','Presidente');


/************* MODIFICACION 30/10/2015 *************/
CREATE TABLE PF_CIRCUITO_POR_PERSONA (
	ID_REGISTRO number(16,0) primary KEY,
	ID_CIRCUITO number(16,0),
	DNI_SOLICITANTE VARCHAR2(10) NOT NULL,
	FOREIGN KEY (ID_CIRCUITO) references PF_FLUJOS (ID_FLUJO)
);

/************* MODIFICACION 09/11/2015 *************/
ALTER TABLE PF_PERSONAS
ADD CONSTRAINT DNI_UNIQUE UNIQUE (DNI_NIE);

/************* MODIFICACION 25/02/2016 *************/
ALTER TABLE PF_PERSONAS ADD ADJUNTOS_ALERTAS NUMBER(1,0) DEFAULT 0;

/************* MODIFICACION 01/02/2017 *************/
INSERT INTO PF_CAT_BACKOFFICE (ID_BACKOFFICE, CODIGO, DESCRIPCION, USERNAME) values (7,'NAVISION','Consulta Web de Facturas','usuNAVISION');

