package opencanarias.com.services.facade.gestor.documental.v01_00;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-10-28T08:09:29.061Z
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "GestorDocumentalService", 
                  wsdlLocation = "http://test-sede.puertosdetenerife.gob.es:8089/APTAEFacadeWS/GestorDocumental/Service?wsdl",
                  targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00") 
public class GestorDocumentalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.opencanarias/services/facade/gestor/documental/v01_00", "GestorDocumentalService");
    public final static QName GestorDocumentalServicePort = new QName("http://com.opencanarias/services/facade/gestor/documental/v01_00", "GestorDocumentalServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://test-sede.puertosdetenerife.gob.es:8089/APTAEFacadeWS/GestorDocumental/Service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestorDocumentalService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://test-sede.puertosdetenerife.gob.es:8089/APTAEFacadeWS/GestorDocumental/Service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestorDocumentalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestorDocumentalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorDocumentalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestorDocumentalService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestorDocumentalService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestorDocumentalService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IGestorDocumentalService
     */
    @WebEndpoint(name = "GestorDocumentalServicePort")
    public IGestorDocumentalService getGestorDocumentalServicePort() {
        return super.getPort(GestorDocumentalServicePort, IGestorDocumentalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGestorDocumentalService
     */
    @WebEndpoint(name = "GestorDocumentalServicePort")
    public IGestorDocumentalService getGestorDocumentalServicePort(WebServiceFeature... features) {
        return super.getPort(GestorDocumentalServicePort, IGestorDocumentalService.class, features);
    }

}
