
package opencanarias.com.services.facade.gestor.documental.v01_00;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-10-28T08:09:28.947Z
 * Generated source version: 2.6.0
 */

@SuppressWarnings("serial")
@WebFault(name = "GestorDocumentalFacadeException", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00")
public class GestorDocumentalFacadeException_Exception extends Exception {
    
    private opencanarias.com.services.facade.gestor.documental.v01_00.GestorDocumentalFacadeException gestorDocumentalFacadeException;

    public GestorDocumentalFacadeException_Exception() {
        super();
    }
    
    public GestorDocumentalFacadeException_Exception(String message) {
        super(message);
    }
    
    public GestorDocumentalFacadeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GestorDocumentalFacadeException_Exception(String message, opencanarias.com.services.facade.gestor.documental.v01_00.GestorDocumentalFacadeException gestorDocumentalFacadeException) {
        super(message);
        this.gestorDocumentalFacadeException = gestorDocumentalFacadeException;
    }

    public GestorDocumentalFacadeException_Exception(String message, opencanarias.com.services.facade.gestor.documental.v01_00.GestorDocumentalFacadeException gestorDocumentalFacadeException, Throwable cause) {
        super(message, cause);
        this.gestorDocumentalFacadeException = gestorDocumentalFacadeException;
    }

    public opencanarias.com.services.facade.gestor.documental.v01_00.GestorDocumentalFacadeException getFaultInfo() {
        return this.gestorDocumentalFacadeException;
    }
}
