package opencanarias.com.services.facade.gestor.documental.v01_00;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-10-28T08:09:29.024Z
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", name = "IGestorDocumentalService")
@XmlSeeAlso({ObjectFactory.class})
public interface IGestorDocumentalService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerVisualizacionDocumento", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ObtenerVisualizacionDocumento")
    @WebMethod
    @ResponseWrapper(localName = "obtenerVisualizacionDocumentoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ObtenerVisualizacionDocumentoResponse")
    public java.lang.String obtenerVisualizacionDocumento(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "actualizarNodo", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ActualizarNodo")
    @WebMethod
    @ResponseWrapper(localName = "actualizarNodoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ActualizarNodoResponse")
    public java.lang.String actualizarNodo(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultarNodo", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ConsultarNodo")
    @WebMethod
    @ResponseWrapper(localName = "consultarNodoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.ConsultarNodoResponse")
    public java.lang.String consultarNodo(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "moverNodo", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.MoverNodo")
    @WebMethod
    @ResponseWrapper(localName = "moverNodoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.MoverNodoResponse")
    public java.lang.String moverNodo(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "crearNodo", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.CrearNodo")
    @WebMethod
    @ResponseWrapper(localName = "crearNodoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.CrearNodoResponse")
    public java.lang.String crearNodo(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eliminarNodo", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.EliminarNodo")
    @WebMethod
    @ResponseWrapper(localName = "eliminarNodoResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.EliminarNodoResponse")
    public java.lang.String eliminarNodo(
        @WebParam(name = "parametros", targetNamespace = "")
        java.lang.String parametros
    ) throws GestorDocumentalFacadeException_Exception;

    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://com.opencanarias/services/facade/gestor/documental/v01_00", className = "opencanarias.com.services.facade.gestor.documental.v01_00.GetVersionResponse")
    public java.lang.String getVersion() throws GestorDocumentalFacadeException_Exception;
}
